name: FGO Login System

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "30 10 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - name: Install Requeriments
        run: pip install -r https://raw.githubusercontent.com/O-Isaac/FGO-Daily-Login/master/requirements.txt

      - name: Gettings files from Repo
        uses: actions/checkout@v2

      - name: Execute main script
        run: |
          python3 main.py
        env:
          userIds: ${{ secrets.318753927 }}
          authKeys: ${{ secrets.ybbyHL6gS3UbAhxa:iFCWBwAAAAA= }}
          secretKeys: ${{ secrets.mAHl18ajaMnvJvLV:iFCWBwAAAAA= }}
          UserAgent: ${{ secrets.Mozilla/5.0 (Linux; Android 10; SM-A750GN Build/QP1A.190711.020) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.5790.168 Mobile Safari/537.36 OPX/2.1 }}
          fateRegion: ${{ secrets.JP }}
          webhookDiscord: ${{ secrets.https://discord.com/api/webhooks/1026520076033216625/JAAw_5smrlnvpY01Pvsi7X5g3GtsC6jrf-EI-Yx0SvZ9k8F2sj_jf_6qiRUBLV4Wk_eq }}
